Automatic Grafana EC2 startup has been adjusted to use tag correctly, latest dashboard added
k8-proxy/aws-jmeter-test-engine pull request #104
Opened 2020-11-05 11:26 UTC by Ali-J2

- ec2_instance_manager.py now looks at value of tag with key "Name" when determining which instance to start up
- LatestDashboard.json has been updated to use the latest version of the Grafana dashboard used with testing

2020-11-05 15:33 UTC, jpoolGW requested changes
Still need a couple of changes to the dashboard. Contact me if you have any questions

2020-11-05 15:33 UTC, jpoolGW commented on jmeter-icap-poc/scripts/LatestDashboard.json
>  	"overwrite": true
Changes in here look good.
Is it possible to add ppt transaction to failure response times as well, I believe this is missing from there
Also in the break down of error codes can you add a measurement for 555 failure code?

2020-11-05 16:18 UTC, Ali-J2 commented on jmeter-icap-poc/scripts/LatestDashboard.json
>  	"overwrite": true
Great, just pushed the changes requested, please let me know if they have any issues, thanks!

2020-11-06 08:32 UTC, jpoolGW approved these changes

2020-11-06 08:32 UTC, merged