Unzipping Malware double zip
k8-proxy/aws-jmeter-test-engine pull request #159
Opened 2020-11-26 20:21 UTC by MaNe2020

2020-11-27 16:34 UTC, jpoolGW requested changes
Looks good, one minor change needed. Jmeter log file is included with PR, there's no need to keep this file.
File can either be removed or added to git ignore file

2020-11-27 16:34 UTC, jpoolGW commented on jmeter.log
> +2020-11-26 21:00:07,879 INFO o.a.j.JMeter: IP: 127.0.1.1 Name: W-R90T5KVP FullName: W-R90T5KVP.localdomain
Log file not needed, please remove from repo

2020-11-30 21:58 UTC, MaNe2020 commented
@jpoolGW jmeter.log file should be deleted now

2020-12-01 11:24 UTC, jpoolGW approved these changes

2020-12-01 11:24 UTC, merged