how to create new test data documentation
k8-proxy/aws-jmeter-test-engine pull request #458
Opened 2021-03-21 18:05 UTC by uzfarid

2021-03-25 16:53 UTC, NadHodeGW requested changes

2021-03-25 16:53 UTC, NadHodeGW commented on jmeter-icap/instructions/How to prepare the test data.md
> +**Note**: Upload Test Data to S3 bucket feature uploads only the test data provided by the framework internally and not any new test data.
Im not too sure of the message here, can you clarify.

2021-03-25 16:53 UTC, NadHodeGW commented on jmeter-icap/instructions/How to prepare the test data.md
> +The framework UI interface allows to upload new CSV test data metada file. It is in UI -> Setup page.
typo in 'metada' should be 'metadata'

2021-03-25 16:53 UTC, NadHodeGW commented on jmeter-icap/instructions/How to prepare the test data.md
> +Once the CSV file containing above meta-data is ready, then actual test files should be uploaded to the test data bucket. It is better to prepare them locally and then upload to the s3 bucket. The st
typo in 'metada' should be 'metadata'

2021-03-25 16:53 UTC, NadHodeGW commented on jmeter-icap/instructions/How to prepare the test data.md
> +The framework comes to setup sample test data and the data should be uploaded to the s3 test data bucket as described in documentation in above link.
is this meant to say: ' The framework comes with sample test data'?

2021-03-25 20:50 UTC, uzfarid commented on jmeter-icap/instructions/How to prepare the test data.md
> +**Note**: Upload Test Data to S3 bucket feature uploads only the test data provided by the framework internally and not any new test data.
it is as it says. what other clarification is needed.

2021-03-29 11:39 UTC, jpoolGW commented on jmeter-icap/instructions/How to prepare the test data.md
> +**Note**: Upload Test Data to S3 bucket feature uploads only the test data provided by the framework internally and not any new test data.
Can be rephrased as
"Upload Test Data option refers only to specific sample test data contained within this repo"

2021-03-31 08:16 UTC, jpoolGW approved these changes

2021-03-31 08:19 UTC, merged