Add files via upload
k8-proxy/aws-jmeter-test-engine pull request #70
Opened 2020-10-21 13:34 UTC by alex-addweb

2020-10-23 07:45 UTC, jpoolGW requested changes

2020-10-23 07:45 UTC, jpoolGW commented on aws-secret-manager_with_-iam-role.json
> +                "RoleName" : "Secret-Manager-Role",
Update role name to AWS-TestEngine-IAMRole

2020-10-23 07:45 UTC, jpoolGW commented on aws-secret-manager_with_-iam-role.json
> +                            ]
Please update policy to access the specific secret. I will provide the secret ARN on slack when requested
Please also add a policy for S3 access. I will also provide ARN for the bucket

2020-10-26 05:35 UTC, alex-addweb commented
@jpoolGW , S3 permission added and secretsmanager permission has been changed. Kindly chec and confirm

2020-10-26 11:26 UTC, jpoolGW requested changes

2020-10-26 11:26 UTC, jpoolGW commented on jmeter-icap-poc/cloudformation/aws-secret-manager_with_-iam-role.json
> +    }
This is not the correct implementation.

We need a single role with IAM Policies for the required permissions.

2020-10-27 08:09 UTC, jpoolGW requested changes

2020-10-27 08:09 UTC, jpoolGW commented on jmeter-icap-poc/cloudformation/aws-secret-manager_with_-iam-role.json
> +                                    "s3.amazonaws.com"
I think this is to allow services access to this role. The role will be accessed by EC2

2020-10-27 08:23 UTC, jpoolGW approved these changes

2020-10-27 08:23 UTC, merged