Logic for handling malware zip files
k8-proxy/aws-jmeter-test-engine pull request #80
Opened 2020-10-23 14:13 UTC by MaNe2020

- zip file is extracted two times
- second extraction is using password
- after usage file is deleted

2020-10-26 15:10 UTC, jpoolGW requested changes

2020-10-26 15:10 UTC, jpoolGW commented on jmeter-icap-poc/scripts/malwareFiles/unzipDataFile.jmx
> +            <stringProp name="Argument.value">${__P(p_password,infected)}</stringProp>
Please confirm whether this value is correct password or not. If it is it needs to be removed and the password will need to be changed

2020-10-26 15:10 UTC, jpoolGW commented on jmeter-icap-poc/scripts/malwareFiles/unzipDataFile.jmx
> +            <stringProp name="Argument.value">${__P(p_bucket,faridpcre)}</stringProp>
This default value should be updated to aws-testengine-s3

2020-10-26 15:10 UTC, jpoolGW commented on jmeter-icap-poc/scripts/malwareFiles/unzipDataFile.jmx
> +            <stringProp name="Argument.value">${__P(p_aws_region,us-east-1)}</stringProp>
This default value should be eu-west-1

2020-10-26 22:25 UTC, uzfarid commented
@MaNe2020 plz have a look at above comments

2020-10-27 06:12 UTC, MaNe2020 commented on jmeter-icap-poc/scripts/malwareFiles/unzipDataFile.jmx
> +            <stringProp name="Argument.value">${__P(p_password,infected)}</stringProp>
@jpoolGW it is correct one. Do you want me to change it here and put some dummy value or to ask test-data team to change it to smth completely different. Also, where we are going to store this sensitive data?

2020-10-27 09:35 UTC, MaNe2020 commented
@jpoolGW and @uzfarid committed requested changes

2020-11-27 12:02 UTC, closed without merging