Icapmonitoring
k8-proxy/aws-jmeter-test-engine pull request #84
Opened 2020-10-27 04:30 UTC by uzfarid

icap monitoring script and fixed hash check logic in main script

2020-10-30 11:56 UTC, jpoolGW requested changes

2020-10-30 11:56 UTC, jpoolGW commented on jmeter-icap-poc/scripts/files.csv
> +15,"tornado2.pdf","pdf/0d746c47dceebea9c39d1a16d0b6e28ccdb995a7","203866 bytes","pdf",False,"0d746c47dceebea9c39d1a16d0b6e28ccdb995a7","462b4d2502205ee2b6ec81ba076a29847aebc4ff","2020-10-23 17:03:08.
This version of the file has quotes surrounding data. We have updated in another PR. Please remove this file to avoid merge conflicts or overwriting correct data set up

2020-10-30 11:56 UTC, jpoolGW commented on IcapMonitoring.jmx
> +</jmeterTestPlan>
There are two files with this name being added in separate locations within the repo. Please make sure only what's required is checked in

2020-10-30 11:56 UTC, jpoolGW commented on jmeter-icap-poc/scripts/ICAP-POC_s3.jmx
>  MessageDigest out_Digest = MessageDigest.getInstance(&quot;SHA-256&quot;);
This version of the script is still using SHA-256 not SHA-1.
Do we need to update this version of the script?

2020-10-30 11:56 UTC, jpoolGW commented on jmeter-icap-poc/scripts/ICAP_Direct_FileProcessing_v1.jmx
> +</jmeterTestPlan>
Does this need to be checked in? As there is another branch checking in a more up to date version of this script?

2020-10-30 11:56 UTC, jpoolGW commented on jmeter-icap-poc/scripts/IcapMonitoring.jmx
> +            <stringProp name="Argument.value">${__P(p_bucket,faridpcre)}</stringProp>
Non Glasswall resources should not be referenced in scripts. Please update default bucket name to aws-testengine-s3

2020-11-03 01:26 UTC, uzfarid commented
I think we could simply just close this PR?

2020-11-03 15:29 UTC, closed without merging