Add parameters to the script
k8-proxy/aws-jmeter-test-engine pull request #91
Opened 2020-11-01 16:41 UTC by pranaysahith

2020-11-03 10:57 UTC, jpoolGW requested changes

2020-11-03 10:57 UTC, jpoolGW commented on .github/workflows/run_tests.yaml
>            INFLUX_HOST: ${{ secrets.INFLUX_HOST }}
Add parameter here for data source file

2020-11-03 10:57 UTC, jpoolGW commented on jmeter-icap-poc/scripts/config.env.sample
> +GRAFANA_URL=10.112.0.112:3000
Put place holder here as this is not correct value

2020-11-03 20:16 UTC, pranaysahith commented on .github/workflows/run_tests.yaml
>            INFLUX_HOST: ${{ secrets.INFLUX_HOST }}
Added TEST_DATA_FILE env variable

2020-11-03 20:16 UTC, pranaysahith commented on jmeter-icap-poc/scripts/config.env.sample
> +GRAFANA_URL=10.112.0.112:3000
added a placeholder

2020-11-04 11:10 UTC, jpoolGW approved these changes

2020-11-04 11:11 UTC, merged